apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: default
  source:
    path   : "front"
    repoURL: "git@github.com:abazunts/devclub-devops-argocd.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
