

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    project: frontend-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
